### ISSUE TITLE
wrap-restful-response

### ISSUE THREAD

**Issue by maxweber** [ngrunwald/ring-middleware-format#33]
Hi,

first of all thank you for creating this great library. We've been using this library for the edn handling. However when I tried to enable support for JSON I discovered this issue:
In https://github.com/ngrunwald/ring-middleware-format/blob/master/src/ring/middleware/format_response.clj#L337

```clojure
   :transit-json (make-encoder wrap-transit-json-response
                               "application/transit+json" :binary)
```
it has to be something like this:
```clojure
   :transit-json (make-encoder (make-transit-encoder :json {})
                               "application/transit+json" :binary)
```
Same for :transit-msgpack below only with :msgpack. At the moment I'm using the single middlewares for edn and transit, which work pretty fine.

Best regards

Max

**Comment by ngrunwald** [comment]
fixed by #26
