### ISSUE TITLE
Nested maps.

### ISSUE THREAD

**Issue by danielsz** [ngrunwald/ring-middleware-format#34]
Hi, 

I'm sending nested Clojure maps over the wire with clj-http (transit+json is set as the content-type). 
On the other side, where ring-middleware-format is used, the maps are transformed into json arrays. 

In other words, this is what is happening:

This goes in:
```clojure
{:twitter {:access-token-response {:user_id "123577893"}}}
```
This goes out:
```clojure
:params {"twitter[access-token-response][user_id]"
		 "123577893"}. 
```

What I would like to achieve: 

This goes in:

```clojure
{:twitter {:access-token-response {:user_id "123577893"}}}
````

This goes out:

```clojure
:params {:twitter {:access-token-response {:user_id "123577893"}}}
```

Or in other words, how do I serialize/deserialize nested Clojure maps?

Thank you in advance.

**Comment by Deraen** [comment]
Can't reproduce.
