### ISSUE TITLE
Check for com.ibm.icu/icu4j alternatives

### ISSUE THREAD

**Issue by Deraen** [ngrunwald/ring-middleware-format#50]
icu4j takes 24MB uncompressed and 10MB as compressed.

Would be great if there is some more lightweight alternative for [charset detection](https://github.com/ngrunwald/ring-middleware-format/blob/master/src/ring/middleware/format_params.clj#L23)

**Comment by cgore** [comment]
How are you going about measuring that?

A quick google search gives me the following:
- Perhaps [clj-det-enc](https://github.com/hozumi/clj-det-enc) based on [juniversalchardet](https://code.google.com/p/juniversalchardet/)
- Maybe [Pantomime](https://github.com/michaelklishin/pantomime), not sure?  It's based on [Apache Tika](http://tika.apache.org/)

**Comment by Deraen** [comment]
http://mvnrepository.com/artifact/com.ibm.icu/icu4j/55.1 10MB
And for uncompressed size, I checked size of `com/ibm/icu` in uberjar archive.

**Comment by Deraen** [comment]
icu4j seems to be still the best alternative.
