### ISSUE TITLE
How to extend the Transit writer to support more types?

### ISSUE THREAD

**Issue by pate** [ngrunwald/ring-middleware-format#59]
I need to support writing `org.joda.time.DateTime` to transit. How would I extend the Transit writer used by the middleware?

**Comment by Deraen** [comment]
Something like this: https://gist.github.com/Deraen/eb3f650c472fb1abe970#file-transit-cljc

And by providing options to the middleware (example from Compojure-api but should give idea for other uses):

```clj
(api
  {:format {:params-opts   {:transit-json {:handlers transit-dates/readers}}
            :response-opts {:transit-json {:handlers transit-dates/writers}}}}
  ...)
```

**Comment by Deraen** [comment]
Closing this as there should be no problem here.
