### ISSUE TITLE
Problem upgrading to JDK 11 due to transitive dependency with issues

### ISSUE THREAD

**Issue by Odinodin** [ngrunwald/ring-middleware-format#71]
The clj-yaml:0.5.5 dependency depends on org.flatland/ordered:1.5.3 which has issues with JDK 11.   See https://github.com/circleci/clj-yaml/issues/22

**Comment by danielcompton** [comment]
Version [1.5.7](https://github.com/clj-commons/ordered/releases/tag/1.5.7) of ordered has a fix for this, so you could either override the flatland dependency here, or wait for clj-yaml to cut a new release with the fix.

**Comment by mikeThurmond** [comment]
I just created a pull request here https://github.com/ngrunwald/ring-middleware-format/pull/72

looks like clj-yaml has been updated? https://github.com/circleci/clj-yaml 

Though I'm not certain it is on clojars or not

**Comment by mikeThurmond** [comment]
pull request here https://github.com/ngrunwald/ring-middleware-format/pull/73

**Comment by Deraen** [comment]
0.7.3 is now released.
